---
  - include_vars: 
      dir: "../../network/defaults"

  - name: Create {{vm_web_name}} virtual machine
    azure_rm_virtualmachine:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      name: "{{vm_web_name}}"
      admin_username: "{{vm_web_username}}"
      image:
        offer: "{{vm_web_image_offer}}"
        publisher: "{{vm_web_image_publisher}}"
        sku: "{{vm_web_image_sku}}"
        version: "{{vm_web_image_version}}"
      location: "{{vm_web_location}}"
      managed_disk_type: "Standard_LRS"
      network_interface_names: "{{nic_web_name}}"
      ssh_password_enabled: False
      ssh_public_keys:
        - path: "/home/{{vm_web_username}}/.ssh/authorized_keys"
          key_data: "{{vm_web_ssh}}"
      vm_size: "{{vm_web_size}}"
      state: present
  