---
  - name: Add additional repos
    yum_repository:
      name: "{{item.name}}"
      description: "{{item.description}}"
      baseurl: "{{item.baseurl}}"
      gpgkey: "{{item.gpg}}"
      gpgcheck: "{{item.gpgcheck}}"
      state: present
    with_items: "{{repo}}"
    become: true

  - name: Install yum packages
    yum:
      name: "{{packages}}"
      state: present
    become: true