---
  - name: Copy nginx conf template
    template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
    notify: restart nginx
    become: true

  - name: Copy site conf template
    template:
      src: "site.conf.j2"
      dest: "/etc/nginx/conf.d/{{item.domain}}.conf"
    with_items: "{{domains}}"
    notify: restart nginx
    become: true

  - name: Enable nginx
    systemd:
      name: "nginx"
      enabled: true
    become: true

  - name: Start nginx
    systemd:
      name: "nginx"
      state: "started"
    become: true