---
- name: Create {{group_name}} vpc
  ec2_vpc_net:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    cidr_block: "{{vpc_cidr}}"
    name: "{{vpc_name}}"
    region: "{{region}}"
    state: present
    tags:
      group: "{{group_name}}"
  register: vpc

- name: Create {{group_name}} private subnet
  ec2_vpc_subnet:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    cidr: "{{subnet_private_cidr}}"
    region: "{{region}}"
    state: present
    tags:
      Name: "{{subnet_private_name}}"
      group: "{{group_name}}"
    vpc_id: "{{vpc.vpc.id}}"

- name: Create {{group_name}} public subnet
  ec2_vpc_subnet:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    cidr: "{{subnet_public_cidr}}"
    region: "{{region}}"
    state: present
    tags:
      Name: "{{subnet_public_name}}"
      group: "{{group_name}}"
    vpc_id: "{{vpc.vpc.id}}"
  register: public_subnet

- name: Create {{group_name}} igw
  ec2_vpc_igw:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{region}}"
    state: present
    #tags:
    #  Name: "{{group_name}}-igw"
    #  group: "{{group_name}}"
    vpc_id: "{{vpc.vpc.id}}"
  register: igw

- name: Create {{group_name}} public route table
  ec2_vpc_route_table:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{region}}"
    routes:
      - dest: "{{route_table_public_dest}}"
        gateway_id: "{{igw.gateway_id}}"
    state: present
    subnets:
      - "{{public_subnet.subnet.id}}"
    tags:
      Name: "{{route_table_public_name}}"
      group: "{{group_name}}"
    vpc_id: "{{vpc.vpc.id}}"
