---
- name: Get {{group_name}} vpc info
  ec2_vpc_net_facts:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      "tag:Name": "{{vpc_name}}"
    region: "{{vpc_region}}"
  register: vpc 

- name: Teardown {{group_name}} igw
  ec2_vpc_igw:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{vpc_region}}"
    state: absent
    vpc_id: "{{vpc.vpcs[0].id}}"
  
- name: Teardown {{group_name}} vpc
  ec2_vpc_net:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    cidr_block: "{{vpc_cidr}}"
    name: "{{vpc_name}}"
    region: "{{vpc_region}}"
    state: absent