---
  - name: Install Postgresql rpm
    yum:
      name: "{{rpm}}"
      state: present
    become: true

  - name: Install yum packages
    yum:
      name: "{{item}}"
      state: present
    with_items: "{{packages}}"
    become: true