---
  - name: Provision db server
    hosts: db
    roles:
      - role: common
      - role: db
    tags: db

  - name: Provision web server
    hosts: web
    roles:
      - role: common
      - role: web
    tags: web
