---
  - name: Destroy {{nic_db_name}} network interface
    azure_rm_networkinterface:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      virtual_network_name: "{{virtual_network_name}}"
      subnet_name: "{{subnet_private_name}}"
      name: "{{nic_db_name}}"
      state: absent

  - name: Destroy {{subnet_private_name}} subnet
    azure_rm_subnet:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      virtual_network_name: "{{virtual_network_name}}"
      name: "{{subnet_private_name}}"
      state: absent

  - name: Destroy {{nsg_private_name}} network server group
    azure_rm_securitygroup:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      name: "{{nsg_private_name}}"
      state: absent