---
  - name: Destroy {{nic_web_name}} network interface
    azure_rm_networkinterface:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      virtual_network_name: "{{virtual_network_name}}"
      subnet_name: "{{subnet_public_name}}"
      name: "{{nic_web_name}}"
      state: absent
  
  - name: Destroy {{nsg_public_name}} network server group
    azure_rm_securitygroup:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      name: "{{nsg_public_name}}"
      state: absent

  - name: Destroy {{ip_name}} public ip
    azure_rm_publicipaddress:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      name: "{{ip_name}}"
      state: absent

  - name: Destroy {{subnet_public_name}} subnet
    azure_rm_subnet:
      client_id: "{{azure_client_id}}"
      secret: "{{azure_secret}}"
      tenant: "{{azure_tenant}}"
      subscription_id: "{{azure_subscription}}"
      resource_group: "{{resource_group_name}}"
      virtual_network_name: "{{virtual_network_name}}"
      name: "{{subnet_public_name}}"
      state: absent