---
# AWS Keys
aws_access_key: "{{vault_aws_access_key}}"
aws_secret_key: "{{vault_aws_secret_key}}"

group_name: jenkins

# VPC
vpc_cidr: 10.0.0.0/24
vpc_name: "{{group_name}}-vpc"
vpc_region: eu-west-2