---
  - name: Enable docker
    systemd:
      name: "docker"
      enabled: true
    become: true

  - name: Start docker
    systemd:
      name: "docker"
      state: "started"
    become: true

  - name: Pull latest docker image
    docker_image:
      name: "{{item.1}}"
      tag: "{{docker_infos[item.0].tag}}"
      state: present
      source: pull
      force_source: true
    with_indexed_items:
      - "{{docker_images}}"
    become: true

  - name: Start docker image
    docker_container:
      name: "{{docker_infos[item.0].container}}"
      image: "{{item.1}}:{{docker_infos[item.0].tag}}"
      ports: "{{docker_infos[item.0].ports}}"
      env: "{{docker_infos[item.0].env}}"
      state: started
    with_indexed_items:
      - "{{docker_images}}"
    become: true
