---
  - name: Copy nginx conf template
    template:
      src: "nginx/nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
    notify: restart nginx
    become: true

  - name: Ensure site conf exists
    template:
      src: nginx/conf.d/{{item.1}}.conf.j2
      dest: /etc/nginx/conf.d/{{item.1}}.conf
    loop: "{{domains|subelements('subdomains')}}"
    notify: restart nginx
    become: true

  - name: Enable nginx
    systemd:
      name: "nginx"
      enabled: true
    become: true

  - name: Start nginx
    systemd:
      name: "nginx"
      state: "started"
    become: true

  - seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
    become: true