---
- name: Get {{group_name}} vpc info
  ec2_vpc_net_facts:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    filters:
      "tag:Name": "{{vpc_name}}"
    region: "{{region}}"
  register: vpc

- name: Teardown {{group_name}} ec2 security group
  ec2_group:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    name: "{{ec2_sg_name}}"
    region: "{{region}}"
    state: absent
    vpc_id: "{{vpc.vpcs[0].id}}"

- name: Teardown {{group_name}} elb security group
  ec2_group:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    name: "{{elb_sg_name}}"
    region: "{{region}}"
    state: absent
    vpc_id: "{{vpc.vpcs[0].id}}"

- name: Teardown {{group_name}} bastion security group
  ec2_group:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    name: "{{bastion_sg_name}}"
    region: "{{region}}"
    state: absent
    vpc_id: "{{vpc.vpcs[0].id}}"