---
repo:
  - docker:
    name: "docker-ce"
    description: "Docker"
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable/"
    gpg: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true
  - epel:
    name: "epel-7"
    description: "EPEL"
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpg: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    gpgcheck: true
  - elastic:
    name: "elastic"
    description: "elastic"
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpg: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: true

packages:
  - "docker-ce"
  - "python-docker-py"
  - "certbot-nginx"
  - "nginx"
  - "filebeat"

#docker_tag: "latest"
docker_infos:
  - tag: "0.2.0"
    container: "home"
    ports: "8080:80"
    env: {}
  - tag: "0.3.0"
    container: "skyrim-tool"
    ports: "5000:8080"
    env: {}
  - tag: "0.1.0"
    container: "ffviii"
    ports: "6000:80"
    env: {}

certificate_path: "/etc/letsencrypt/"