---
repo:
  - docker:
    name: "docker-ce"
    description: "Docker"
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable/"
    gpg: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true
  - epel:
    name: "epel-7"
    description: "EPEL"
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpg: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    gpgcheck: true

packages:
  - "docker-ce"
  - "python-docker-py"
  - "certbot-nginx"
  - "nginx"

#docker_tag: "latest"
docker_infos:
  - tag: "0.2.1"
    container: "app"
    ports: "8080:80"
    env:
      FOF_CONNECTION_STRING: "postgresql://{{db_fof_user}}:{{db_fof_user_password}}@{{db_host}}:5432/{{db_fof}}"
      DVDRENTAL_CONNECTION_STRING: "postgresql://{{db_dvdrental_user}}:{{db_dvdrental_user_password}}@{{db_host}}:5432/{{db_dvdrental}}"
  - tag: "0.1.0"
    container: "skyrim-tool"
    ports: "5000:8080"
    env: {}

certificate_path: "/etc/letsencrypt/"