---
  - name: restart nginx
    service: 
      name: "nginx"
      state: "restarted"
    become: true

  - name: restart filebeat
    service: 
      name: "filebeat"
      state: "restarted"
    become: true